### ISSUE TITLE
[BE] ERD 

### ISSUE THREAD

**Issue by cocojen** [codesquad-member-2020/issue-tracker-10#24]
<img width="1199" alt="스크린샷 2020-06-12 오후 2 10 08" src="https://user-images.githubusercontent.com/52371228/84467394-fa34a180-acb6-11ea-86a6-8360c75ac5b2.png">

**Comment by sigridjineth** [comment]
@cocojen 이거 무슨 툴인가요? 워크벤치 쓰고 있는데 훨씬 보기 좋네요.
